### ISSUE TITLE
Alternative service / continuity

### ISSUE THREAD

**Issue by ferrisoxide** [carlos-a-rodriguez/datakick#1]
Hey @carlos-a-rodriguez 

You're probably aware that datakick.org is shutting down soon. Just letting you know that I'm building out a potential replacement here: https://www.brocade.io. 

It's not a full replacement for the current Datakick API, but it's heading in that direction. Keen to work you or anyone else wanting to keep a free/open product database going, and continue working on libraries to support that.

- Tom

**Comment by carlos-a-rodriguez** [comment]
I've added a note to the documentation indicating that datakick.org has shutdown. This package will receive no further updates.
