### ISSUE TITLE
New URL for DataKick

### ISSUE THREAD

**Issue by JessiDunbar** [carlos-a-rodriguez/datakick#2]
Hi Carlos,

I'm writing to you to let you know that datakick recently ceased operation and their API is no longer functioning. A company I represent has acquired the database and re-uploaded it to the new domain: https://gtinsearch.org/

It still functions in exactly the same way and retains all the information and API from the old domain. I just thought I'd let you know in case you'd like to update your article to include this recent change. 

Best Regards,
Jessi
Reitec LLC

**Comment by carlos-a-rodriguez** [comment]
I've added a note to the documentation indicating that datakick.org has shutdown. This package will receive no further updates.
